// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Hilaladiii/aureus/internal/delivery/handler"
	"github.com/Hilaladiii/aureus/internal/delivery/middleware"
	"github.com/Hilaladiii/aureus/internal/repository"
	"github.com/Hilaladiii/aureus/internal/server"
	"github.com/Hilaladiii/aureus/internal/usecase"
	"github.com/Hilaladiii/aureus/internal/worker"
	"github.com/Hilaladiii/aureus/pkg/config"
	"github.com/Hilaladiii/aureus/pkg/jwt"
)

// Injectors from injector.go:

func InitializeApp() (*server.App, error) {
	env, err := config.LoadEnv()
	if err != nil {
		return nil, err
	}
	db := config.NewDB(env)
	userRepo := repository.NewUserRepo(db)
	jwtItf, err := jwt.NewJwt(env)
	if err != nil {
		return nil, err
	}
	userUsecase := usecase.NewUserUsecase(userRepo, jwtItf)
	validate := config.NewValidator()
	userHandler := handler.NewUserHandler(userUsecase, validate)
	categoryRepo := repository.NewCategoryRepo(db)
	categoryUsecase := usecase.NewCategoryUsecase(categoryRepo)
	categoryHandler := handler.NewCategoryHandler(categoryUsecase, validate)
	walletRepo := repository.NewWalletRepo(db)
	walletUsecase := usecase.NewWalletUsecase(walletRepo, env)
	walletHandler := handler.NewWalletHandler(walletUsecase, validate, env)
	auctionRepo := repository.NewAuctionRepo(db)
	bidRepo := repository.NewBidRepo(db)
	seaweedFSStorage := config.NewSeaweedFSStorage(env)
	txManagerItf := config.NewTxManager(db)
	auctionUsecase := usecase.NewAuctionUsecase(auctionRepo, walletRepo, bidRepo, seaweedFSStorage, txManagerItf)
	auctionHandler := handler.NewAuctionHandler(auctionUsecase, validate)
	middlewareMiddleware := middleware.NewMiddleware(jwtItf)
	router := server.NewRouter(userHandler, categoryHandler, walletHandler, auctionHandler, middlewareMiddleware)
	app := server.NewFiberServer(router)
	client := config.NewRedisClient(env)
	auctionWorker := worker.NewAuctionWorker(client, auctionUsecase)
	serverApp := server.NewApp(app, auctionWorker)
	return serverApp, nil
}
