// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Hilaladiii/aureus/internal/delivery/handler"
	"github.com/Hilaladiii/aureus/internal/delivery/middleware"
	"github.com/Hilaladiii/aureus/internal/delivery/router"
	"github.com/Hilaladiii/aureus/internal/delivery/server"
	"github.com/Hilaladiii/aureus/internal/repository"
	"github.com/Hilaladiii/aureus/internal/usecase"
	"github.com/Hilaladiii/aureus/pkg/config"
	"github.com/Hilaladiii/aureus/pkg/jwt"
	"github.com/gofiber/fiber/v3"
)

// Injectors from injector.go:

func InitializeApp() (*fiber.App, error) {
	env, err := config.LoadEnv()
	if err != nil {
		return nil, err
	}
	db := config.NewDB(env)
	userRepo := repository.NewUserRepo(db)
	jwtItf, err := jwt.NewJwt(env)
	if err != nil {
		return nil, err
	}
	userUsecase := usecase.NewUserUsecase(userRepo, jwtItf)
	validate := config.NewValidator()
	userHandler := handler.NewUserHandler(userUsecase, validate)
	categoryRepo := repository.NewCategoryRepo(db)
	categoryUsecase := usecase.NewCategoryUsecase(categoryRepo)
	categoryHandler := handler.NewCategoryHandler(categoryUsecase, validate)
	walletRepo := repository.NewWalletRepo(db)
	walletUsecase := usecase.NewWalletUsecase(walletRepo, env)
	walletHandler := handler.NewWalletHandler(walletUsecase, validate, env)
	middlewareMiddleware := middleware.NewMiddleware(jwtItf)
	routerRouter := router.NewRouter(userHandler, categoryHandler, walletHandler, middlewareMiddleware)
	app := server.NewFiberServer(routerRouter)
	return app, nil
}
